# Generated by Django 4.1.5 on 2023-01-25 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_no', models.CharField(help_text="donor's mobile number", max_length=13)),
                ('blood_group', models.CharField(choices=[('B+', 'B_POSITIVE'), ('A+', 'A_POSITIVE'), ('O+', 'O_POSITIVE'), ('AB+', 'AB_POSITIVE')], default='B+', max_length=10)),
                ('user_type', models.CharField(choices=[('DONOR', 'DONOR'), ('RECIPIENT', 'RECIPIENT'), ('STAFF', 'STAFF')], default='DONOR', max_length=50)),
                ('last_donation_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('donation_area', models.CharField(help_text="donor's donation area", max_length=100)),
                ('permanent_address', models.CharField(help_text="donor's permanent address", max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('user', models.ForeignKey(help_text="donor's first name", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
