# Generated by Django 4.1.5 on 2023-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B_POSITIVE'), ('A+', 'A_POSITIVE'), ('O+', 'O_POSITIVE'), ('AB+', 'AB_POSITIVE'), ('B-', 'B_NEGATIVE'), ('A-', 'A_NEGATIVE'), ('O-', 'O_NEGATIVE'), ('AB-', 'AB_NEGATIVE')], default='B+', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(help_text="donor's mobile number"),
        ),
    ]
