# Generated by Django 4.1.5 on 2023-01-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0002_alter_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(choices=[('B+', 'B_POSITIVE'), ('A+', 'A_POSITIVE'), ('O+', 'O_POSITIVE'), ('AB+', 'AB_POSITIVE'), ('B-', 'B_NEGATIVE'), ('A-', 'A_NEGATIVE'), ('O-', 'O_NEGATIVE'), ('AB-', 'AB_NEGATIVE')], default='B+', max_length=10)),
                ('whole_blood', models.IntegerField(blank=True)),
                ('frozen_plasma', models.IntegerField(blank=True)),
                ('platelet', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
