# Generated by Django 4.1.5 on 2023-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0003_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(choices=[('DONATE', 'STORAGE_INCREASE'), ('TAKE', 'STORAGE_TAKE')], default='DONATE', max_length=20),
        ),
    ]
